"""Static branding assets for CodeStrata HTML reports."""

from __future__ import annotations

import base64
from functools import lru_cache
from importlib.resources import files

BRAND_NAME = "CodeStrata"
BRAND_REPORT_NAME = "Engineering Assessment"
BRAND_REPORT_TITLE = f"{BRAND_NAME} {BRAND_REPORT_NAME}"
BRAND_FOOTER_LINE = "Generated by CodeStrata Community Edition"
BRAND_VERSION = "0.1.0"


@lru_cache(maxsize=1)
def logo_data_uri() -> str:
    """Return a data URI for the CodeStrata logo (embedded, aspect ratio preserved)."""

    payload = files("aimf.reporting.assets").joinpath("codestrata-logo.png").read_bytes()
    encoded = base64.standard_b64encode(payload).decode("ascii")
    return f"data:image/png;base64,{encoded}"
