"""Technical debt assessment domain package (Phase 4.3.1 / 4.3.4A)."""

from aimf.domain.technical_debt.assessment.enums import (
    TechnicalDebtAssessmentStatus,
    TechnicalDebtCoverageAreaStatus,
    TechnicalDebtCoverageMaturity,
    TechnicalDebtLimitationCategory,
    TechnicalDebtSourceRole,
    TechnicalDebtTraceabilityRelation,
)
from aimf.domain.technical_debt.assessment.identifiers import (
    SECTION_ID,
    SECTION_SCHEMA_VERSION,
    TECHNICAL_DEBT_ASSESSMENT_FILENAME,
    build_configuration_fingerprint,
    build_empty_section_fingerprint,
    build_hotspot_id,
    build_limitation_id,
    build_trace_edge_id,
)
from aimf.domain.technical_debt.assessment.models import (
    TechnicalDebtAssessmentSection,
    TechnicalDebtCoverageArea,
    TechnicalDebtCoverageSummary,
    TechnicalDebtExecutionSummary,
    TechnicalDebtFindingInventory,
    TechnicalDebtFindingReference,
    TechnicalDebtHotspot,
    TechnicalDebtHotspotInventory,
    TechnicalDebtLimitation,
    TechnicalDebtObservedMetric,
    TechnicalDebtRoleInventory,
    TechnicalDebtTraceabilityEdge,
    TechnicalDebtTraceabilityIndex,
)

__all__ = [
    "SECTION_ID",
    "SECTION_SCHEMA_VERSION",
    "TECHNICAL_DEBT_ASSESSMENT_FILENAME",
    "TechnicalDebtAssessmentSection",
    "TechnicalDebtAssessmentStatus",
    "TechnicalDebtCoverageArea",
    "TechnicalDebtCoverageAreaStatus",
    "TechnicalDebtCoverageMaturity",
    "TechnicalDebtCoverageSummary",
    "TechnicalDebtExecutionSummary",
    "TechnicalDebtFindingInventory",
    "TechnicalDebtFindingReference",
    "TechnicalDebtHotspot",
    "TechnicalDebtHotspotInventory",
    "TechnicalDebtLimitation",
    "TechnicalDebtLimitationCategory",
    "TechnicalDebtObservedMetric",
    "TechnicalDebtRoleInventory",
    "TechnicalDebtSourceRole",
    "TechnicalDebtTraceabilityEdge",
    "TechnicalDebtTraceabilityIndex",
    "TechnicalDebtTraceabilityRelation",
    "build_configuration_fingerprint",
    "build_empty_section_fingerprint",
    "build_hotspot_id",
    "build_limitation_id",
    "build_trace_edge_id",
]
